### ISSUE TITLE
Snap installed trippy on Ubuntu get permission denied while accessing config file

### ISSUE THREAD

**Issue by helixzz** [fujiapple852/trippy#1058] opened 2024-03-21 06:53 UTC
**Describe the bug**
Just installed trippy from snap store using command `snap install trippy`. It works fine with default config. If I want to customize anything (for default behavior) it seems the only way is to create a config file (e.g. `trippy.toml`). However, with the snap installed version of trippy, the trippy binary seems can't read the config file under my $HOME directory, even if the dir and file permissions are set to 777.

**To Reproduce**
```
snap install trippy
trip --print-config-template > ~/.config/trippy.toml
jqadmin@xxx:~$ trippy connect.helixzz.com
Error: config file not found: "/home/xxx/.config/trippy.toml"

Caused by:
    Permission denied (os error 13)
```

**Expected behavior**
trippy reads the config file and perform its configuration correctly.

**Environment Info**
- OS: Ubuntu 22.04.2 LTS
- Trippy version: trip 0.9.0
- Installation method: snap
- Terminal / Console: SSH session connected to my host with Tabby

**Comment by fujiapple852** [comment] 2024-03-21 07:23
Thanks for the report @helixzz.

I suspect trippy needs to connect to the `home` interface to allow this. 

if you connect it manually (as described in https://snapcraft.io/docs/home-interface) does that fix the issue?

if so I will ask for that interface to be added to the snap for the nest version.

**Comment by helixzz** [comment] 2024-03-21 09:59
> Thanks for the report @helixzz.
> 
> I suspect trippy needs to connect to the `home` interface to allow this.
> 
> if you connect it manually (as described in https://snapcraft.io/docs/home-interface) does that fix the issue?
> 
> if so I will ask for that interface to be added to the snap for the nest version.

Thanks for your reply!

I've tried `sudo snap connect trippy:home :home` and it seems produces an error: `error: snap "trippy" has no plug named "home"`. Maybe I haven't get the correct command line?

**Comment by fujiapple852** [comment] 2024-03-21 11:26
@helixzz thanks for trying. I guess I need to add it to here first and release it:

https://github.com/fujiapple852/trippy/blob/fe534c2eb25a6d51d17ee3a35fc68a56dfecffc1/snap/snapcraft.yaml#L73-L75

Leave it with me and I’ll figure out what is needed.

**Comment by fujiapple852** [comment] 2024-03-21 13:58
I am able to reproduce the issue on a ubuntu instance.

I added the `home` interface to trippy (in #1059) and this was build and pushed to the `edge` channel (revision 2643).  

I switched to the `edge` channel and refreshed:

```
snap-id:      MuyJc7aas4HVkKbWZclsIhu0R9WAjX50
tracking:     latest/edge
refresh-date: today at 13:00 UTC
channels:
  latest/stable:    0.9.0 2023-11-30 (1943) 3MB -
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      0.9.0 2024-03-21 (2643) 3MB -
installed:          0.9.0            (2643) 3MB -
```

I connected the (now available) `home` interface:

```
fuji@trippy-dev:~$ sudo snap connections trippy
Interface        Plug                    Slot              Notes
home             trippy:home             :home             -
network          trippy:network          :network          -
network-bind     trippy:network-bind     :network-bind     -
network-observe  trippy:network-observe  :network-observe  -
```

But it still does not work:

```
fuji@trippy-dev:~$ sudo trip 1.1.1.1 --config-file /home/fuji/trippy.toml
Error: config file not found: "/home/fuji/trippy.toml"

Caused by:
    Permission denied (os error 13)
```

The same message is given for files that do not exist:

```
fuji@trippy-dev:~$ sudo trip 1.1.1.1 --config-file /home/fuji/doesnotexist.toml
Error: config file not found: "/home/fuji/doesnotexist.toml"

Caused by:
    Permission denied (os error 13)
```

I tried from `/tmp` as well but that does not work either (which seems [expected](https://askubuntu.com/questions/1263843/how-to-allow-snap-applications-to-access-tmp-folder)), however it fails with a different error (the files _does_ exist in this case):

```
fuji@trippy-dev:~$ sudo trip 1.1.1.1 --config-file /tmp/trippy.toml
Error: config file not found: "/tmp/trippy.toml"

Caused by:
    No such file or directory (os error 2)
```

Aside, note that I used a non-hidden file and dirs above as the `home` interface only claims to allow access to non-hidden files.  For hidden files it seems another interface, [`personal-files`](https://snapcraft.io/docs/personal-files-interface) is needed.  However I haven't tried this since I have not even been able to get the non-hidden files to work so far.  There is also a [`removal-media`](https://snapcraft.io/docs/removable-media-interface) interface which may be needed.

I'll post a question on the snapcraft [forum](https://forum.snapcraft.io/) as i'm not a regular snap user or expert and the solution is not obvious.

**Comment by fujiapple852** [comment] 2024-03-21 14:17
Posted: https://forum.snapcraft.io/t/access-config-file-from-snap/39418

**Comment by fujiapple852** [comment] 2024-03-23 09:48
Added #1062 to allow running via `snap` without requiring sudo such that the `home` and `personal-files` interfaces will allow access to configuration files in the `/home` of the original user rather than the home of  the `root` user.

**Comment by fujiapple852** [comment] 2024-03-27 12:21
@helixzz if you are following the thread on the snapcraft forum, there is a solution to allow trippy (any snap really) to read files from $HOME.  The catch is it doesn't support hidden files or directories and so you'd need to place your `trippy.toml` file in your $HOME directory.  This change will be included in 0.10.0 snap release of Trippy (due very soon).

**Comment by fujiapple852** [comment] 2024-03-31 10:09
I'm awaiting the change to be approved by the snap folk and without that the `0.10.0` release will not be available in the snap store.  Rather than block the whole Trippy release (which I'm planning to do today) i'm going to go ahead and close this issue and add it to the `0.10.0` release note as completed.  Once the approval happens I can release `0.10.0` to the snap store.

**Closed by fujiapple852** 2024-03-31 10:09 UTC
Labels: bug, package

**Comment by fujiapple852** [comment] 2024-04-17 05:47
@helixzz Trippy 0.10.0 has finally been released on snap and supports the ability to read (non-hidden) configuration files.
