### ISSUE TITLE
bug: `/etc/hosts` is not respected

### ISSUE THREAD

**Issue by notramo** [fujiapple852/trippy#533] opened 2023-04-30 14:02 UTC
`trippy` doesn't respect the content of `/etc/hosts`

**Comment by fujiapple852** [comment] 2023-04-30 15:57
Thank you for the bug report @notramo.  Can you confirm:
- The OS you are running on
- The trippy version
- The trippy command line arguments, in particular whether you are using the  `-r, --dns-resolve-method` flags
- if the issue is with resolving hostnames to IPs or reverse lookup of hostnames from IPs 

By default, trippy uses the libc provided `getaddrinfo` and `getnameinfo` functions (indirectly via the [dns-lookup](https://crates.io/crates/dns-lookup) crate.

**Comment by fujiapple852** [comment] 2023-05-06 01:19
Thanks @notramo, we can leave this open for now. 

Note that musl builds have been re-enabled for 0.8.0 (they were disabled for 0.7.0 due to https://github.com/fujiapple852/trippy/issues/456)

I’m not familiar with Void Linux, is there a package manager / repository that trippy could be added to so that it can be installed on that platform?

**Comment by fujiapple852** [comment] 2023-05-15 13:37
@notramo 0.8.0 has been released and includes a musl build: https://github.com/fujiapple852/trippy/releases/tag/0.8.0

**Closed** 2023-05-15 15:26 UTC
Labels: bug, dns, triage
