### ISSUE TITLE
0.3.0 fails on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [fujiapple852/trippy#142] opened 2022-05-08 10:08 UTC
Hi,
I've just built 0.3.0 on NetBSD but, I'm holding the package update for now.

```
$ please trip www.google.com
Error: unknown default interface
```

while,
```
$ ping www.google.com
PING www.google.com (142.250.74.36): 56 data bytes
64 bytes from 142.250.74.36: icmp_seq=0 ttl=114 time=7.558233 ms
64 bytes from 142.250.74.36: icmp_seq=1 ttl=114 time=4.214741 ms
64 bytes from 142.250.74.36: icmp_seq=2 ttl=114 time=7.050889 ms
64 bytes from 142.250.74.36: icmp_seq=3 ttl=114 time=4.714395 ms
64 bytes from 142.250.74.36: icmp_seq=4 ttl=114 time=4.501966 ms
64 bytes from 142.250.74.36: icmp_seq=5 ttl=114 time=4.196851 ms
^C
----www.google.com PING Statistics----
6 packets transmitted, 6 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.196851/5.372846/7.558233/1.517096 ms
```

This was not the case in version 0.2.0

Any thoughts? I haven't gone through the changes.

**Comment by fujiapple852** [comment] 2022-05-08 11:42
Thank you for reporting this @0323pin.

I think is caused by https://github.com/fujiapple852/trippy/pull/80/commits/afd96e368da10a743e3a3c5a218aa80d68737a2c which was part of the fix in https://github.com/fujiapple852/trippy/pull/80.  Specifically the new [`discover_default_src_addr`](https://github.com/fujiapple852/trippy/blob/9082e270c4c0286ce8f1c9ded60960737480a5e7/src/tracing/net.rs#L323-L347) function uses a `pnet` function that comes with [health warning](https://docs.rs/pnet/latest/pnet/datalink/fn.interfaces.html).

I planned to replace that function with https://github.com/fujiapple852/trippy/issues/133 (which is closer to what `mtr` does) anyway, so I'll work on that next and issue a `0.3.1` version.  I'll let know when when done.

Thanks again for the help!

**Comment by 0323pin** [comment] 2022-05-08 19:08
@fujiapple852 Cool, thanks!
I'll wait for 0.3.1 then :)

**Comment by fujiapple852** [comment] 2022-05-09 06:21
@0323pin #133 is merged and so this should be resolved.  Can you try from the [`0.3.1`](https://github.com/fujiapple852/trippy/tree/0.3.1) tag please?

**Comment by 0323pin** [comment] 2022-05-09 06:28
> @0323pin #133 is merged and so this should be resolved. Can you try from the [`0.3.1`](https://github.com/fujiapple852/trippy/tree/0.3.1) tag please?

Sure, I'll do it later today. I won't have access to my machine until later in the afternoon.
I'll let you know :)
Thanks!

**Comment by 0323pin** [comment] 2022-05-09 11:53
@fujiapple852 😞 

```
pin:home/pin/ $ please trip www.google.com
Error: IO error: Address family not supported by protocol family (os error 47)

Caused by:
    Address family not supported by protocol family (os error 47)
pin:home/pin/ $ trip -V
trippy 0.3.1
```

**Comment by fujiapple852** [comment] 2022-05-09 13:24
@0323pin thanks for retrying.  

Realistically, i'll need to be able to access a NetBSD to machine to test and debug this as the behaviour differs from both macOS and Linux.

After reading [this](https://wiki.netbsd.org/amazon_ec2/) guide I was able to spin up a NetBSD EC2 instance using the [NetBSD testing arm64 9.99.86](https://aws.amazon.com/marketplace/pp/prodview-kts7ehlvm33la?sr=0-1&ref_=beagle&applicationId=AWSMPContessa) AMI (as the ones listed [here](https://wiki.netbsd.org/amazon_ec2/amis/) seems to be out of date).  I'm a complete novice at using NetBSD and wasn't able to get `pkgin` installed using `pkg_add` after playing around with it for a while, I'm probably just doing the wrong thing.

Are you able to advise on getting a NetBSD environment setup?  I'm happy to give you access to the throwaway EC2 host I created.

**Comment by fujiapple852** [comment] 2022-05-09 14:43
I am now able to build and run `trippy` on NetBSD and can recreate the 2nd error.  

The problem looks to be related to IPv6 which is not yet supported by Trippy (see https://github.com/fujiapple852/trippy/issues/35).  Specifically, when using the OS resolver (which is the default) on NetBSD, the first address returned for `www.google.com` is the IPv6 address (`2607:f8b0:4004:c06::93`) which isn't handled and so leads to the error.

The fix, until IPv6 support is implemented, should be to filter out IPv6 addresses during DNS resolution.  I will test this out tomorrow.

Aside: I am able to _avoid_ the error by bypassing the OS DNS resolver, i.e. `trip www.google.com -r resolv`.  

Note that I was also able to reproduce the issue on `0.2.0` as well, so I don't think this is new to `0.3.x`, though it may manifest itself differently.

**Comment by 0323pin** [comment] 2022-05-09 16:22
@fujiapple852 Thank you!
All good now, I'll merge the update tonight together with another package.

> On the plus side, I am now able to build and test it on NetBSD, so that'll be useful in the future anyway!

Nice!
Would you mind dropping me a line on an e-mail anyway, I'd like to ask you a few things about your set-up. It might be just what I've been looking for. Thanks!
pin [at] NetBSD [dot] org

**Closed** 2022-05-09 17:23 UTC
Labels: bug
